name = "jd-app"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-04-28"
main = "./.output/server/index.mjs"

workers_dev = false

[env.dev]
routes = ["dev.joculdemocratiei.ro/*"]

[env.production]
routes = ["joculdemocratiei.ro/*"]

[assets]
directory = "./.output/public/"
binding = "ASSETS"

[observability]
enabled = true

[[services]]
binding     = "GAME_BACKEND"
service     = "jd-game-backend-local"

[[env.dev.services]]
binding     = "GAME_BACKEND"
service     = "jd-game-backend-dev"

[[env.production.services]]
binding     = "GAME_BACKEND"
service     = "jd-game-backend-production"

[[env.local.services]]
binding     = "GAME_BACKEND"
service     = "jd-game-backend-local"

[env.production.vars]
ENVIRONMENT = "production"
VITE_API_URL = "https://gs.joculdemocratiei.ro/api"

[env.dev.vars]
ENVIRONMENT = "dev"
VITE_API_URL = "https://dev.gs.joculdemocratiei.ro/api"

[env.local.vars]
ENVIRONMENT = "local"
VITE_API_URL = "http://localhost:4201/api"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "4200"
simple = { limit = 100, period = 60 }

[[env.production.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "4200"
simple = { limit = 100, period = 60 }

[[env.dev.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "4200"
simple = { limit = 100, period = 60 }

[[env.local.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "4200"
simple = { limit = 100, period = 60 }
